name: Coverage

on:
  push:
    branches: [ "master" , "release/*" ]
  pull_request:
    branches: [ "master" , "release/*"]

jobs:

  coverage:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    # - name: download dependencies
    #   run: go mod download
      
    - name: Calc coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1
    
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov