name: Lint

on:
  push:
    branches: [ "master" , "release/*" ]
  pull_request:
    branches: [ "master" , "release/*"]

jobs:

  lint:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    # - name: download dependencies
    #   run: go mod download

    - name: Run linters
      uses: golangci/golangci-lint-action@v3